import { orderTypes } from "@shopx/types"
import { Schema, SchemaDefinition, Types } from "mongoose"

const { ObjectId } = Types

const orderSchema: SchemaDefinition<orderTypes> = {
  dateClosed: Number,
  datePaid: Number,
  dateCancelled: Number,
  number: Number,
  shippingStatus: String,
  items: [
    {
      id: ObjectId,
      productID: ObjectId,
      variantID: Number,
      quantity: Number,
      discountTotal: Number,
      name: String,
      price: Number,
      priceTotal: Number,
      sku: String,
      taxClass: String,
      taxTotal: Number,
      variantName: String,
      weight: Number,
    },
  ],
  transactions: [String],
  discounts: [Number],
  billingAddress: {
    fullName: String,
    address1: String,
    address2: String,
    city: String,
    country: String,
    postalCode: String,
    state: String,
    phone: String,
    company: String,
    taxNumber: String,
    coordinates: {
      latitude: String,
      longitude: String,
    },
    details: String,
  },
  shippingAddress: {
    fullName: String,
    address1: String,
    address2: String,
    city: String,
    country: String,
    postalCode: String,
    state: String,
    phone: String,
    company: String,
    taxNumber: String,
    coordinates: { latitude: String, longitude: String },
    details: String,
  },
  taxRate: Number,
  shippingTax: Number,
  shippingDiscount: Number,
  shippingPrice: Number,
  itemTaxIncluded: Boolean,
  shippingTaxIncluded: Boolean,
  closed: Boolean,
  cancelled: Boolean,
  delivered: Boolean,
  paid: Boolean,
  hold: Boolean,
  draft: Boolean,
  firstName: String,
  lastName: String,
  password: String,
  email: String,
  mobile: String,
  referrerUrl: String,
  landingUrl: String,
  channel: String,
  note: String,
  comments: String,
  coupon: String,
  trackingNumber: String,
  customerID: ObjectId,
  statusID: Number,
  paymentMethodID: ObjectId,
  paymentReceipt: [
    {
      id: ObjectId,
      alt: String,
      position: Number,
      filename: String,
    },
  ],
  shippingMethodID: ObjectId,
  tags: [String],
}

export const order = new Schema<orderTypes>(orderSchema, { timestamps: true })
