import { userTypes } from "@shopx/types"
import { Schema, SchemaDefinition, Types } from "mongoose"

const { ObjectId } = Types
// TODO check for userAgent and remove as required

const userSchema: SchemaDefinition<userTypes> = {
  email: String,
  mobile: String,
  fullName: String,
  firstName: String,
  lastName: String,
  password: String,
  gender: String,
  groupID: ObjectId,
  socialAccounts: [String],
  addresses: [String],
  browser: {
    ip: String,
    userAgent: String,
  },
  permissions: {
    read: {
      appSettings: Boolean,
      checkoutFields: Boolean,
      customerGroups: Boolean,
      customers: Boolean,
      emailSettings: Boolean,
      emailTemplates: Boolean,
      files: Boolean,
      orders: Boolean,
      pages: Boolean,
      paymentGateways: Boolean,
      paymentMethods: Boolean,
      productCategories: Boolean,
      products: Boolean,
      redirects: Boolean,
      settings: Boolean,
      shippingMethods: Boolean,
      themeSettings: Boolean,
      users: Boolean,
      webhooks: Boolean,
    },
    create: {
      appSettings: Boolean,
      checkoutFields: Boolean,
      customerGroups: Boolean,
      customers: Boolean,
      emailSettings: Boolean,
      emailTemplates: Boolean,
      files: Boolean,
      orders: Boolean,
      pages: Boolean,
      paymentGateways: Boolean,
      paymentMethods: Boolean,
      productCategories: Boolean,
      products: Boolean,
      redirects: Boolean,
      settings: Boolean,
      shippingMethods: Boolean,
      themeSettings: Boolean,
      users: Boolean,
      webhooks: Boolean,
    },
    update: {
      appSettings: Boolean,
      checkoutFields: Boolean,
      customerGroups: Boolean,
      customers: Boolean,
      emailSettings: Boolean,
      emailTemplates: Boolean,
      files: Boolean,
      orders: Boolean,
      pages: Boolean,
      paymentGateways: Boolean,
      paymentMethods: Boolean,
      productCategories: Boolean,
      products: Boolean,
      redirects: Boolean,
      settings: Boolean,
      shippingMethods: Boolean,
      themeSettings: Boolean,
      users: Boolean,
      webhooks: Boolean,
    },
    delete: {
      appSettings: Boolean,
      checkoutFields: Boolean,
      customerGroups: Boolean,
      customers: Boolean,
      emailSettings: Boolean,
      emailTemplates: Boolean,
      files: Boolean,
      orders: Boolean,
      pages: Boolean,
      paymentGateways: Boolean,
      paymentMethods: Boolean,
      productCategories: Boolean,
      products: Boolean,
      redirects: Boolean,
      settings: Boolean,
      shippingMethods: Boolean,
      themeSettings: Boolean,
      users: Boolean,
      webhooks: Boolean,
    },
  },
}

export const user = new Schema<userTypes>(userSchema, { timestamps: true })
